language: node_js
node_js:
  - "8"

install: 
  - yarn
  - npm run build-storybook

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
